language: python

env:
  - TOX_ENV=py36
  - TOX_ENV=cov COVERAGE=1

before_install:
    - "[ ! -z $COVERAGE ] && travis_retry pip install coveralls || true"
    
# To install dependencies, tell tox to do everything but actually running the test.
install:
    - travis_retry pip install tox
    - travis_retry pip install -r requirements.txt
    - travis_retry tox -e $TOX_ENV --notest

script: tox -e $TOX_ENV


# coveralls.io reporting
after_success:
    - "[ ! -z $COVERAGE ] && coveralls || true"
